server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring
    static_configs:
      - targets: ['localhost']
        labels:
          job: spring
          __path__: /tmp/spring_logs/*.log